### ISSUE TITLE
Create a Java SDK for the electronic ID card (CIE)

### ISSUE THREAD

**Issue by alranel** [italia/cie-nis-java-sdk#3]
As of now this repository contains example code rather than a true library/SDK. It should be turned into a library with a documented API in order to allow developers to include it.

**Mentor**: This is a broad task, with several possible mentors: ask on the #cie channel on https://slack.developers.italia.it once you start having a basic idea

**Comment by asha15** [comment]
@alranel Shall i work on this issue, if it's still open?

**Comment by fventola-ipzs** [comment]
new repo update
